spring:
  cors:
    allowed-origins:
      - "http://localhost:4200"
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
    allowed-headers:
      - "Origin"
      - "Access-Control-Allow-Origin"
      - "Content-Type"
      - "Accept"
      - "Jwt-Token"
      - "Authorization"
      - "Origin, Accept"
      - "X-Requested-With"
      - "Access-Control-Request-Method"
      - "Access-Control-Request-Headers"
      - "Access-Control-Allow-Origin"
      - "Access-Control-Allow-Credentials"
      - "Filename"
      - "AUTHORIZATION"
    allow-credentials: true
    
eureka:
 client:
  register—with—eureka: true
  fetch—registry: true
  service—url:
   defaul tZone: http://localhost:8761/eureka/
  instance:
   hostname: localhost 
