web:
  cors:
    allowed-origins: "http://localhost:4200"
    allowed-methods: "GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD"
    max-age: 3600
    allowed-headers: "Requestor-Type"
    exposed-headers: "X-Get-Header"
eureka:
 client:
  register—with—eureka: true
  fetch—registry: true
  service—url:
   defaul tZone: http://localhost:8761/eureka/
  instance:
   hostname: localhost 
